name: 'Jupydiff'
description: 'Diff Jupyter Notebooks in Repo'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository.(https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ secrets.GITHUB_TOKEN }}
 body:
    description: 'The contents of the comment.'
    required: true
  path:
    description: 'Relative path of the file to comment on.'
  position:
    description: 'Line index in the diff to comment on.'
  runs:
    using: 'ubuntu'
    main: 'main.yml'