name: 'jupydiff'
description: 'Create a comment with diff info for a commit on .ipynb files'

inputs:
  token:
    description: 'GitHub authentication token to access the repo'
    default: ${{ github.token }}
  repository:
    description: 'Name of repo where to print jupydiff changes'
    default: ${{ github.repository }}
    
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
