on: push
name: Notebook Differ
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
         python-version: 3.8

      - name: Install dependencies
        run: |
         pip install --upgrade nbdime
         pip install nodejs
      - name: Retrieving Previous Commit
        run: git reset --soft HEAD~1

      - name: Run Jupyter Notebook Diff
        run: 
         for f in *.ipynb; 
         do nbdime diff --no-color -s $f >> output.txt;
         done
       
      - id: get-comment-body
        run: |
          body=$(cat output.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
          
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - run: npm install @actions/core
             npm install @actions/github

      - name: Display Changes in Commit Comment
        
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          body: |
            ```diff
            ${{ steps.get-comment-body.outputs.body }}
            ```
